Cleanups for the GatewayWebSocketConnection class and related code:
1. Rename the package holding the GatewayWebSocketConnection class from
   `handlers` to `connections`.

2. Make the serverapp call to the `close_all` method on the websocket connection
   class more resilient.

   Specifically, the `self.kernel_websocket_connection_class.close_all()` method invocation
   relies on two different attribute lookups, either of which might fail:

   1. The `self.kernel_websocket_connection_class` lookup can raise an AttributeError
      if the method that sets the default value of that trait raises an AttributeError.
      That, in turn, occurs when the `self.gateway_config` attribute is not yet set
      because the `initialize` method has not yet been invoked.

      During server startup this scenario is gracefully handled, but during cleanup
      it was previously not.

   2. The `self.kernel_websocket_connection_class.close_all` lookup can fail if the
      provided class does not implement the `close_all` class method.

   For both cases, we catch the raised AttributeError and treat it as a no-op.

3. Remove the `close_all` method from the GatewayWebSocketConnection class since it
   was a no-op, and is no longer required by serverapp.