Import User unconditionally
It is used in a cast on line 617, rather than just a type annotation.
Without this, requests fail with:

```
[E 2024-01-09 18:30:53.736 SingleUserNotebookApp web:1871] Uncaught exception GET /user/yuvi.panda@utoronto.ca/lab (10.1.0.10)
    HTTPServerRequest(protocol='https', host='jupyter.utoronto.ca', method='GET', uri='/user/yuvi.panda@utoronto.ca/lab', version='HTTP/1.1', remote_ip='10.1.0.10')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 1765, in _execute
        result = await result  # type: ignore
                 ^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 616, in prepare
        user = User(self.get_current_user())
               ^^^^
    NameError: name 'User' is not defined
```